{% set name = "pytest-mpi" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad392f5cd3f72ed0aeb9bb9e6f77554d79f3b81f72e3526ba60ae34fc2d4359e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest
  run:
    - pytest

test:
  imports:
    - pytest_mpi

about:
  home: https://github.com/aragilar/pytest-mpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Pytest plugin for working with MPI
  doc_url: https://pytest-mpi.readthedocs.io/

extra:
  recipe-maintainers:
    - beckermr
